In [1]:
import pandas as pd
import numpy as np

In [2]:
hl=pd.read_excel(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\wilber\historicallocations.xlsx')
hl.info()

<class 'pandas.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sequence     279 non-null    int64
 1   Unit         279 non-null    str
 2   Events       279 non-null    str
 3   Date         279 non-null    str
 4   Landmark     0 non-null      float64
 5   Address      277 non-null    str
 6   Speed        279 non-null    int64
 7   Temperature  0 non-null      float64
 8   Driver       0 non-null      float64
 9   Latitude     279 non-null    float64
 10  Longitude    279 non-null    float64
dtypes: float64(5), int64(2), str(4)
memory usage: 24.1 KB

In [3]:
hl['Events'].value_counts()

Events
Travel Stop         74
Travel Start        74
Towing/Drifting?    59
Parked              30
POWER UP            17
Drive               15
Ignition OFF         4
Ignition ON          4
Idle Alert           1
Idle - Stop          1
Name: count, dtype: int64

In [5]:
hl_ignition=hl[hl['Events'].str.contains('Ignition')]
hl_ignition

,Sequence,Unit,Events,Date,Landmark,Address,Speed,Temperature,Driver,Latitude,Longitude
259,20,JG-18T,Ignition OFF,May 17 2026 01:56 PM,NaN,"Av Siberia Cota, Bogota, Cundinamarca, Colombia",0,NaN,NaN,4.760309,-74.156134
261,18,JG-18T,Ignition ON,May 17 2026 01:55 PM,NaN,"Av Siberia Cota, Bogota, Cundinamarca, Colombia",0,NaN,NaN,4.760309,-74.156134
262,17,JG-18T,Ignition ON,May 17 2026 01:55 PM,NaN,"Av Siberia Cota, Bogota, Cundinamarca, Colombia",0,NaN,NaN,4.760309,-74.156134
263,16,JG-18T,Ignition OFF,May 17 2026 01:55 PM,NaN,"Av Siberia Cota, Bogota, Cundinamarca, Colombia",0,NaN,NaN,4.760302,-74.156136
265,14,JG-18T,Ignition OFF,May 06 2026 11:18 AM,NaN,"Av Siberia Cota, Bogota, Cundinamarca, Colombia",0,NaN,NaN,4.760308,-74.156122
268,11,JG-18T,Ignition ON,May 06 2026 11:07 AM,NaN,"Av Siberia Cota, Bogota, Cundinamarca, Colombia",0,NaN,NaN,4.760289,-74.156148
272,7,JG-18T,Ignition OFF,May 03 2026 03:26 PM,NaN,"Av Siberia Cota, Bogota, Cundinamarca, Colombia",0,NaN,NaN,4.760303,-74.156137
273,6,JG-18T,Ignition ON,May 03 2026 03:24 PM,NaN,"Av Siberia Cota, Bogota, Cundinamarca, Colombia",0,NaN,NaN,4.760301,-74.156148

In [6]:
hl_drive=hl[hl['Events'].str.contains('Drive')]
hl_drive

,Sequence,Unit,Events,Date,Landmark,Address,Speed,Temperature,Driver,Latitude,Longitude
16,263,JG-18T,Drive,May 25 2026 08:11 AM,NaN,"Cl. 89a Sur #93d-2, Bogotá, Colombia",6,NaN,NaN,4.624087,-74.212634
111,168,JG-18T,Drive,May 21 2026 05:21 PM,NaN,"Av 50, Bogota, Cundinamarca",49,NaN,NaN,4.749002,-74.144471
145,134,JG-18T,Drive,May 21 2026 04:40 PM,NaN,"Kr93-58, Bogota, Cundinamarca, Colombia",14,NaN,NaN,4.719875,-74.094705
149,130,JG-18T,Drive,May 21 2026 04:36 PM,NaN,"Kr91 127dbisa-16, Bogota, Cundinamarca",8,NaN,NaN,4.719501,-74.090490
162,117,JG-18T,Drive,May 21 2026 04:27 PM,NaN,"Kr70g 127-7, Bogota, Cundinamarca",8,NaN,NaN,4.710639,-74.075107
163,116,JG-18T,Drive,May 21 2026 04:27 PM,NaN,"Cl127 70d-90, Bogota, Cundinamarca",6,NaN,NaN,4.710595,-74.075100
184,95,JG-18T,Drive,May 21 2026 07:41 AM,NaN,"South America, Suba, Capital District",11,NaN,NaN,4.755100,-74.064091
185,94,JG-18T,Drive,May 21 2026 07:41 AM,NaN,"Carrera 68 #169a-46 a 169a-98, Bogotá, Bogotá,...",0,NaN,NaN,4.755075,-74.064274
198,81,JG-18T,Drive,May 21 2026 07:29 AM,NaN,"Av Boyaca 128-52, Bogota, Cundinamarca",17,NaN,NaN,4.715571,-74.076254
201,78,JG-18T,Drive,May 21 2026 07:25 AM,NaN,"Entrada A La Cl127-13, Bogota, Cundinamarca",9,NaN,NaN,4.709770,-74.079886
203,76,JG-18T,Drive,May 21 2026 07:25 AM,NaN,"Av. C. 127 #56, Bogotá, Colombia",22,NaN,NaN,4.709495,-74.079575
204,75,JG-18T,Drive,May 21 2026 07:25 AM,NaN,"Av. C. 127 #71d-19, Bogotá, Colombia",20,NaN,NaN,4.709614,-74.079430
205,74,JG-18T,Drive,May 21 2026 07:24 AM,NaN,"Cerros de Niza-cl 127A - Kr 78, Bogotá, Colombia",38,NaN,NaN,4.711762,-74.080074
206,73,JG-18T,Drive,May 21 2026 07:24 AM,NaN,"South America, Usaquén, Capital District",37,NaN,NaN,4.712120,-74.080456
207,72,JG-18T,Drive,May 21 2026 07:24 AM,NaN,"Club Los Lagartos-CL 127A - KR 81, Bogotá, Col...",32,NaN,NaN,4.711366,-74.082226