In [1]:
import pandas as pd
import numpy as np

In [2]:
# This script get the database of events with Odometer that I created in my research.
events=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\zonar\events.csv',sep=';')
events_with_odometer=events[events['Odometer'].str.contains('y')]
df_book_table01=events_with_odometer

In [77]:
raw_data=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ams\Export_grn401_0226.csv',sep=',')
raw_data_columns=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ams\Export_grn401_columns_0226.csv',sep=',')
raw_data_columns['Date']='NaN'
raw_data_columns['Message_Type']='NaN'
raw_data_columns['Message_Type_No_Buff']='NaN'
aux_m=[]
aux_m_nb=[]

for i in range(0,raw_data_columns.shape[0]):
    aux_m.append(raw_data_columns.iloc[i,0][6:11])
    #aux_m_nb.append(raw_data_columns.iloc[i,0])
raw_data_columns['Message_Type']=aux_m

raw_data_columns['Message_Type'].value_counts().to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\columns.csv')
raw_data_columns_aux=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\columns.csv')
raw_data_columns_aux.info()
df_book_table02=raw_data_columns_aux

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Message_Type  16 non-null     str
 1   count         16 non-null     int64
dtypes: int64(1), str(1)
memory usage: 388.0 bytes

In [78]:
df_book_table01.info()
df_book_table02.info()

<class 'pandas.DataFrame'>
Index: 11 entries, 0 to 18
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Message_Type  11 non-null     str
 1   count         11 non-null     int64
 2   Odometer      11 non-null     str
dtypes: int64(1), str(2)
memory usage: 352.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Message_Type  16 non-null     str
 1   count         16 non-null     int64
dtypes: int64(1), str(1)
memory usage: 388.0 bytes

In [79]:
num_filas_table01=int(df_book_table01.shape[0])
num_filas_table02=int(df_book_table02.shape[0])       
cont=0
df_aux=pd.DataFrame()        
list_field01=[]
list_field02=[]
list_field03=[]
list_field04=[]       
#print("df_book_table01[8,0]: ",df_book_table01.iloc[8,0]) #UnitsByDealer.csv_r.csv
#print("df_book_table02[8,5]: ",df_book_table02.iloc[8,5]) #6MB.        
print("\nInformación de las tablas: ")
print("\nTabla 1:")
print(df_book_table01.info())
print("\nTabla 2:")
print(df_book_table02.info())
attribute_name_table01='Message_Type'#Digitar el índice de la tabla 1.#input("\nDigita el atributo a comparar de la tabla 1: ")
attribute_name_table02='Message_Type'#Digitar el índice de la tabla 2.#input("Digita el atribito a comparar de la tabla 2: ")
position_table01=int(df_book_table01.columns.get_loc(attribute_name_table01))
position_table02=int(df_book_table02.columns.get_loc(attribute_name_table02))
print("\nAtributo de la tabla1: ",position_table01)
print("Atributo de la tabla2: ",position_table02,"\n")
print("Trabajando...")                          
for i in range(0,num_filas_table01):
    for j in range(0,num_filas_table02):
        #if str(df_book_table01.iloc[i,5])==str(df_book_table02.iloc[j,3]): 
        if str(df_book_table01.iloc[i,position_table01])==str(df_book_table02.iloc[j,position_table02]):                                                                             
            list_field01.append(df_book_table01.iloc[i,0])
            #list_field02.append(df_book_table02.iloc[j,23])
            #list_field03.append(df_book_table02.iloc[j,21])
            #list_field04.append(df_book_table02.iloc[j,3])
            print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
            print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
            cont=cont+1
df_aux['Event']=list_field01
#df_aux['ICCID']=list_field02
#df_aux['MSISDN']=list_field03
#df_aux['Last Contact On']=list_field04
print("Cont= ",cont)
print(df_aux.info())
#option_exp=input("\n¿Desea generar un reporte de coincidencias en formato csv S/N?\n")
#if option_exp=="S":
df_aux.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\coincidences.csv')                  #Edit
cont=0

print(df_aux)

Información de las tablas:

Tabla 1:
<class 'pandas.DataFrame'>
Index: 11 entries, 0 to 18
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Message_Type  11 non-null     str
 1   count         11 non-null     int64
 2   Odometer      11 non-null     str
dtypes: int64(1), str(2)
memory usage: 352.0 bytes
None

Tabla 2:
<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Message_Type  16 non-null     str
 1   count         16 non-null     int64
dtypes: int64(1), str(1)
memory usage: 388.0 bytes
None

Atributo de la tabla1:  0
Atributo de la tabla2:  0

Trabajando...
df_book_table01[i,position_table01]:  GTFRI  = df_book_table02[j,position_table02]:  GTFRI
df_book_table01[i,position_table01]:  GTIGL  = df_book_table02[j,position_table02]:  GTIGL
df_book_table01[i,position_table01]:  GTIGF  = df_book_table02[j,position_table02]:  GTIGF
df_book_table01[i,position_table01]:  GTIGN  = df_book_table02[j,position_table02]:  GTIGN
df_book_table01[i,position_table01]:  GTHBM  = df_book_table02[j,position_table02]:  GTHBM
df_book_table01[i,position_table01]:  GTRTL  = df_book_table02[j,position_table02]:  GTRTL
df_book_table01[i,position_table01]:  GTDOG  = df_book_table02[j,position_table02]:  GTDOG
df_book_table01[i,position_table01]:  GTSPD  = df_book_table02[j,position_table02]:  GTSPD
df_book_table01[i,position_table01]:  GTIDN  = df_book_table02[j,position_table02]:  GTIDN
df_book_table01[i,position_table01]:  GTIDF  = df_book_table02[j,position_table02]:  GTIDF
Cont=  10
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Event   10 non-null     str
dtypes: str(1)
memory usage: 212.0 bytes
None
   Event
0  GTFRI
1  GTIGL
2  GTIGF
3  GTIGN
4  GTHBM
5  GTRTL
6  GTDOG
7  GTSPD
8  GTIDN
9  GTIDF

grn401

In [80]:
gtfri_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTFRI')]
gtigl_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIGL')]
gtigf_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIGF')]
gtign_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIGN')]
gthbm_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTHBM')]
gttow_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTTOW')]
gtrtl_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTRTL')]
gtdog_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTDOG')]
gtspd_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTSPD')]
gtidn_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIDN')]
gtidf_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIDF')]

date_gtfri=[]
date_gtigl=[]
date_gtigf=[]
date_gtign=[]
date_gthbm=[]
date_gttow=[]
date_gtrtl=[]
date_gtdog=[]
date_gtspd=[]
date_gtidn=[]
date_gtidf=[]

km_gtfri=[]
km_gtigl=[]
km_gtign=[]
km_gtigf=[]
km_gtidn=[]
km_gtidf=[]
km_gtdog=[]
km_gtspd=[]
km_gtrtl=[]
km_gthbm=[]
km_gttow=[]

for i in range(0, gtfri_raw_data.shape[0]):
    date_gtfri.append(str(gtfri_raw_data.iloc[i,13]))    
    km_gtfri.append((float(gtfri_raw_data.iloc[i,20]))*0.621371)
gtfri_raw_data['Date']=date_gtfri
#gtfri_raw_data_eqz329_28_jan2026.info()
gtfri_raw_data['Km in miles']=km_gtfri

for i in range(0, gtigl_raw_data.shape[0]):
    date_gtigl.append(str(gtigl_raw_data.iloc[i,13]))    
    km_gtigl.append((float(gtigl_raw_data.iloc[i,20]))*0.621371)
gtigl_raw_data['Date']=date_gtigl
gtigl_raw_data['Km in miles']=km_gtigl

for i in range(0, gtign_raw_data.shape[0]):
    date_gtign.append(str(gtign_raw_data.iloc[i,13]))    
    km_gtign.append((float(gtign_raw_data.iloc[i,20]))*0.621371)
gtign_raw_data['Date']=date_gtign
gtign_raw_data['Km in miles']=km_gtign

for i in range(0, gtigf_raw_data.shape[0]):
    date_gtigf.append(str(gtigf_raw_data.iloc[i,13]))    
    km_gtigf.append((float(gtigf_raw_data.iloc[i,20]))*0.621371)
gtigf_raw_data['Date']=date_gtigf
gtigf_raw_data['Km in miles']=km_gtigf

for i in range(0, gtidn_raw_data.shape[0]):
    date_gtidn.append(str(gtidn_raw_data.iloc[i,12]))    
    km_gtidn.append((float(gtidn_raw_data.iloc[i,20]))*0.621371)    
gtidn_raw_data['Date']=date_gtidn
gtidn_raw_data['Km in miles']=km_gtidn

for i in range(0, gtidf_raw_data.shape[0]):
    date_gtidf.append(str(gtidf_raw_data.iloc[i,12]))    
    km_gtidf.append((float(gtidf_raw_data.iloc[i,20]))*0.621371)    
gtidf_raw_data['Date']=date_gtidf
gtidf_raw_data['Km in miles']=km_gtidf

for i in range(0, gtdog_raw_data.shape[0]):
    date_gtdog.append(str(gtdog_raw_data.iloc[i,13]))    
    km_gtdog.append((float(gtdog_raw_data.iloc[i,20]))*0.621371)   
gtdog_raw_data['Date']=date_gtdog
gtdog_raw_data['Km in miles']=km_gtdog

for i in range(0, gtspd_raw_data.shape[0]):
    date_gtspd.append(str(gtspd_raw_data.iloc[i,13]))    
    km_gtspd.append((float(gtspd_raw_data.iloc[i,20]))*0.621371)    
gtspd_raw_data['Date']=date_gtspd
gtspd_raw_data['Km in miles']=km_gtspd

for i in range(0, gtrtl_raw_data.shape[0]):
    date_gtrtl.append(str(gtrtl_raw_data.iloc[i,13]))    
    km_gtrtl.append((float(gtrtl_raw_data.iloc[i,20]))*0.621371)    
gtrtl_raw_data['Date']=date_gtrtl
gtrtl_raw_data['Km in miles']=km_gtrtl

for i in range(0, gthbm_raw_data.shape[0]):
    date_gthbm.append(str(gthbm_raw_data.iloc[i,13]))    
    km_gthbm.append((float(gthbm_raw_data.iloc[i,20]))*0.621371)    
gthbm_raw_data['Date']=date_gthbm
gthbm_raw_data['Km in miles']=km_gthbm

for i in range(0, gttow_raw_data.shape[0]):
    date_gttow.append(str(gttow_raw_data.iloc[i,13]))    
    km_gttow.append((float(gttow_raw_data.iloc[i,20]))*0.621371)    
gttow_raw_data['Date']=date_gttow
gttow_raw_data['Km in miles']=km_gttow

gttow_raw_data['Date_str']=str(gttow_raw_data['Date'])

#202601021739
value_to_look=input('Type the first date to searh: ')
gtfri_raw_data_wanted=gtfri_raw_data[gtfri_raw_data['Date'].str.contains(value_to_look)]
gtigl_raw_data_wanted=gtigl_raw_data[gtigl_raw_data['Date'].str.contains(value_to_look)]
gtign_raw_data_wanted=gtign_raw_data[gtign_raw_data['Date'].str.contains(value_to_look)]
gtigf_raw_data_wanted=gtigf_raw_data[gtigf_raw_data['Date'].str.contains(value_to_look)]
gtidn_raw_data_wanted=gtidn_raw_data[gtidn_raw_data['Date'].str.contains(value_to_look)]
gtidf_raw_data_wanted=gtidf_raw_data[gtidf_raw_data['Date'].str.contains(value_to_look)]
gtdog_raw_data_wanted=gtdog_raw_data[gtdog_raw_data['Date'].str.contains(value_to_look)]
gtspd_raw_data_wanted=gtspd_raw_data[gtspd_raw_data['Date'].str.contains(value_to_look)]
gtrtl_raw_data_wanted=gtrtl_raw_data[gtrtl_raw_data['Date'].str.contains(value_to_look)]
gthbm_raw_data_wanted=gthbm_raw_data[gthbm_raw_data['Date'].str.contains(value_to_look)]
gttow_raw_data_wanted=gttow_raw_data[gttow_raw_data['Date_str'].str.contains(value_to_look)]

#print(gtfri_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gtigl_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gtign_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gtigf_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gtidn_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gtidf_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gtdog_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gtspd_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gtrtl_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gthbm_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gttow_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])

result_feb01=pd.concat([gtfri_raw_data_wanted,
                        gtigl_raw_data_wanted,
                        gtign_raw_data_wanted,
                        gtigf_raw_data_wanted,
                        gtidn_raw_data_wanted,
                        gtidf_raw_data_wanted,
                        gtdog_raw_data_wanted,
                        gtspd_raw_data_wanted,
                        gtrtl_raw_data_wanted,
                        gthbm_raw_data_wanted,
                        gttow_raw_data_wanted])
result_feb01

,Message,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Date,Message_Type,Message_Type_No_Buff,Km in miles,Date_str
1,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,766E$,20260201005001,GTFRI,NaN,14282.274572,NaN
3,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,670$",20260201014956,GTFRI,NaN,14282.274572,NaN
5,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,672$",20260201024955,GTFRI,NaN,14282.274572,NaN
9,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,676$",20260201045021,GTFRI,NaN,14282.274572,NaN
11,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,678$",20260201055038,GTFRI,NaN,14282.274572,NaN
13,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,767A$,20260201065128,GTFRI,NaN,14282.274572,NaN
16,+BUFF:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,767C$,20260201075212,GTFRI,NaN,14282.274572,NaN
18,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,767F$,20260201085154,GTFRI,NaN,14282.274572,NaN
20,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,681$",20260201095102,GTFRI,NaN,14282.274572,NaN
22,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,683$",20260201105132,GTFRI,NaN,14282.274572,NaN
24,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,685$",20260201115210,GTFRI,NaN,14282.274572,NaN
26,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,687$",20260201125211,GTFRI,NaN,14282.274572,NaN
28,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,689$",20260201135247,GTFRI,NaN,14282.274572,NaN
32,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,768D$,20260201155229,GTFRI,NaN,14282.274572,NaN
34,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,768F$,20260201165228,GTFRI,NaN,14282.274572,NaN
36,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,691$",20260201175303,GTFRI,NaN,14282.274572,NaN
38,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,693$",20260201185247,GTFRI,NaN,14282.274572,NaN
41,+BUFF:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,695$",20260201195233,GTFRI,NaN,14282.274572,NaN
43,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,"7,698$",20260201205303,GTFRI,NaN,14282.274572,NaN
45,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,769A$,20260201215337,GTFRI,NaN,14282.274572,NaN
47,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,769C$,20260201225303,GTFRI,NaN,14282.274572,NaN
49,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,0.0,342.0,...,NaN,NaN,NaN,2.026020e+13,769E$,20260201235418,GTFRI,NaN,14282.274572,NaN

In [81]:
gtfri_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTFRI')]
gtigl_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIGL')]
gtigf_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIGF')]
gtign_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIGN')]
gthbm_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTHBM')]
gttow_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTTOW')]
gtrtl_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTRTL')]
gtdog_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTDOG')]
gtspd_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTSPD')]
gtidn_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIDN')]
gtidf_raw_data=raw_data_columns[raw_data_columns['Message'].str.contains('GTIDF')]

date_gtfri=[]
date_gtigl=[]
date_gtigf=[]
date_gtign=[]
date_gthbm=[]
date_gttow=[]
date_gtrtl=[]
date_gtdog=[]
date_gtspd=[]
date_gtidn=[]
date_gtidf=[]

km_gtfri=[]
km_gtigl=[]
km_gtign=[]
km_gtigf=[]
km_gtidn=[]
km_gtidf=[]
km_gtdog=[]
km_gtspd=[]
km_gtrtl=[]
km_gthbm=[]
km_gttow=[]

for i in range(0, gtfri_raw_data.shape[0]):
    date_gtfri.append(str(gtfri_raw_data.iloc[i,13]))    
    km_gtfri.append((float(gtfri_raw_data.iloc[i,20]))*0.621371)
gtfri_raw_data['Date']=date_gtfri
#gtfri_raw_data_eqz329_28_jan2026.info()
gtfri_raw_data['Km in miles']=km_gtfri

for i in range(0, gtigl_raw_data.shape[0]):
    date_gtigl.append(str(gtigl_raw_data.iloc[i,13]))    
    km_gtigl.append((float(gtigl_raw_data.iloc[i,20]))*0.621371)
gtigl_raw_data['Date']=date_gtigl
gtigl_raw_data['Km in miles']=km_gtigl

for i in range(0, gtign_raw_data.shape[0]):
    date_gtign.append(str(gtign_raw_data.iloc[i,13]))    
    km_gtign.append((float(gtign_raw_data.iloc[i,20]))*0.621371)
gtign_raw_data['Date']=date_gtign
gtign_raw_data['Km in miles']=km_gtign

for i in range(0, gtigf_raw_data.shape[0]):
    date_gtigf.append(str(gtigf_raw_data.iloc[i,13]))    
    km_gtigf.append((float(gtigf_raw_data.iloc[i,20]))*0.621371)
gtigf_raw_data['Date']=date_gtigf
gtigf_raw_data['Km in miles']=km_gtigf

for i in range(0, gtidn_raw_data.shape[0]):
    date_gtidn.append(str(gtidn_raw_data.iloc[i,12]))    
    km_gtidn.append((float(gtidn_raw_data.iloc[i,20]))*0.621371)    
gtidn_raw_data['Date']=date_gtidn
gtidn_raw_data['Km in miles']=km_gtidn

for i in range(0, gtidf_raw_data.shape[0]):
    date_gtidf.append(str(gtidf_raw_data.iloc[i,12]))    
    km_gtidf.append((float(gtidf_raw_data.iloc[i,20]))*0.621371)    
gtidf_raw_data['Date']=date_gtidf
gtidf_raw_data['Km in miles']=km_gtidf

for i in range(0, gtdog_raw_data.shape[0]):
    date_gtdog.append(str(gtdog_raw_data.iloc[i,13]))    
    km_gtdog.append((float(gtdog_raw_data.iloc[i,20]))*0.621371)   
gtdog_raw_data['Date']=date_gtdog
gtdog_raw_data['Km in miles']=km_gtdog

for i in range(0, gtspd_raw_data.shape[0]):
    date_gtspd.append(str(gtspd_raw_data.iloc[i,13]))    
    km_gtspd.append((float(gtspd_raw_data.iloc[i,20]))*0.621371)    
gtspd_raw_data['Date']=date_gtspd
gtspd_raw_data['Km in miles']=km_gtspd

for i in range(0, gtrtl_raw_data.shape[0]):
    date_gtrtl.append(str(gtrtl_raw_data.iloc[i,13]))    
    km_gtrtl.append((float(gtrtl_raw_data.iloc[i,20]))*0.621371)    
gtrtl_raw_data['Date']=date_gtrtl
gtrtl_raw_data['Km in miles']=km_gtrtl

for i in range(0, gthbm_raw_data.shape[0]):
    date_gthbm.append(str(gthbm_raw_data.iloc[i,13]))    
    km_gthbm.append((float(gthbm_raw_data.iloc[i,20]))*0.621371)    
gthbm_raw_data['Date']=date_gthbm
gthbm_raw_data['Km in miles']=km_gthbm

for i in range(0, gttow_raw_data.shape[0]):
    date_gttow.append(str(gttow_raw_data.iloc[i,13]))    
    km_gttow.append((float(gttow_raw_data.iloc[i,20]))*0.621371)    
gttow_raw_data['Date']=date_gttow
gttow_raw_data['Km in miles']=km_gttow

gttow_raw_data['Date_str']=str(gttow_raw_data['Date'])

#202601021739
value_to_look=input('Type the last date to searh: ')
gtfri_raw_data_wanted=gtfri_raw_data[gtfri_raw_data['Date'].str.contains(value_to_look)]
gtigl_raw_data_wanted=gtigl_raw_data[gtigl_raw_data['Date'].str.contains(value_to_look)]
gtign_raw_data_wanted=gtign_raw_data[gtign_raw_data['Date'].str.contains(value_to_look)]
gtigf_raw_data_wanted=gtigf_raw_data[gtigf_raw_data['Date'].str.contains(value_to_look)]
gtidn_raw_data_wanted=gtidn_raw_data[gtidn_raw_data['Date'].str.contains(value_to_look)]
gtidf_raw_data_wanted=gtidf_raw_data[gtidf_raw_data['Date'].str.contains(value_to_look)]
gtdog_raw_data_wanted=gtdog_raw_data[gtdog_raw_data['Date'].str.contains(value_to_look)]
gtspd_raw_data_wanted=gtspd_raw_data[gtspd_raw_data['Date'].str.contains(value_to_look)]
gtrtl_raw_data_wanted=gtrtl_raw_data[gtrtl_raw_data['Date'].str.contains(value_to_look)]
gthbm_raw_data_wanted=gthbm_raw_data[gthbm_raw_data['Date'].str.contains(value_to_look)]
gttow_raw_data_wanted=gttow_raw_data[gttow_raw_data['Date_str'].str.contains(value_to_look)]

#print(gtfri_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gtigl_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gtign_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gtigf_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gtidn_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gtidf_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gtdog_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gtspd_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gtrtl_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']],'\n',gthbm_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])
#print(gttow_raw_data_wanted[['Message','Date','Unnamed: 20','Km in miles']])

result_feb28=pd.concat([gtfri_raw_data_wanted,
                        gtigl_raw_data_wanted,
                        gtign_raw_data_wanted,
                        gtigf_raw_data_wanted,
                        gtidn_raw_data_wanted,
                        gtidf_raw_data_wanted,
                        gtdog_raw_data_wanted,
                        gtspd_raw_data_wanted,
                        gtrtl_raw_data_wanted,
                        gthbm_raw_data_wanted,
                        gttow_raw_data_wanted])
result_feb28

,Message,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Date,Message_Type,Message_Type_No_Buff,Km in miles,Date_str
15832,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,68.3,178.0,...,NaN,NaN,NaN,2.026023e+13,B3FF$,20260228001438,GTFRI,NaN,15917.163810,NaN
15833,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,103.6,187.0,...,NaN,NaN,NaN,2.026023e+13,B400$,20260228001532,GTFRI,NaN,15918.033730,NaN
15865,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,93.0,201.0,...,NaN,NaN,NaN,2.026023e+13,B402$,20260228001632,GTFRI,NaN,15918.965786,NaN
15894,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,76.5,193.0,...,NaN,NaN,NaN,2.026023e+13,B403$,20260228001732,GTFRI,NaN,15919.773568,NaN
15918,+RESP:GTFRI,500700,868574042918495,NaN,NaN,10,1.0,1.0,102.8,197.0,...,NaN,NaN,NaN,2.026023e+13,B405$,20260228001832,GTFRI,NaN,15920.705625,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16558,+RESP:GTHBM,500700,868574042918495,NaN,NaN,5,1.0,0.0,44.1,22.0,...,NaN,NaN,NaN,NaN,NaN,20260228174550,GTHBM,NaN,16075.861964,NaN
16561,+RESP:GTHBM,500700,868574042918495,NaN,NaN,5,1.0,0.0,54.7,310.0,...,NaN,NaN,NaN,NaN,NaN,20260228174605,GTHBM,NaN,16075.986238,NaN
16564,+RESP:GTHBM,500700,868574042918495,NaN,NaN,5,1.0,0.0,52.6,21.0,...,NaN,NaN,NaN,NaN,NaN,20260228174620,GTHBM,NaN,16076.172649,NaN
16576,+RESP:GTHBM,500700,868574042918495,NaN,NaN,5,1.0,0.0,49.8,107.0,...,NaN,NaN,NaN,NaN,NaN,20260228174808,GTHBM,NaN,16077.042569,NaN
16612,+RESP:GTHBM,500700,868574042918495,NaN,NaN,0,1.0,0.0,34.6,90.0,...,NaN,NaN,NaN,NaN,NaN,20260228181715,GTHBM,NaN,16093.136077,NaN

In [82]:
print("Odometer difference betwwen Feb the 28 and Feb the 01: ",float(result_feb28['Unnamed: 20'].max())-float(result_feb01['Unnamed: 20'].min()))

Odometer difference betwwen Feb the 28 and Feb the 01:  2953.300000000003