In [72]:
import pandas as pd
import numpy as np

Export Alerts Report from TSO.

4764429210	33333333		    85f	55,182

4764429242	972564107	BHI-774	85f	55,182

4764429241	972573025	BHA-863	85f	55,182

4764429268	987457988	BCZ-718	85f	55,182

4764428940	972565498	BCY-928	85f	55,182

In [ ]:
#Test with 4764428940	972565498	BCY-928	85f	55.182.
alerts=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\don_pollo\Alerts Report.csv',sep=',')
alerts.info()

<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GroupName    74 non-null     str
 1   UnitName     74 non-null     str
 2   textbox4     74 non-null     str
 3   StartTime    74 non-null     str
 4   ContactName  74 non-null     str
 5   DriverName   74 non-null     str
 6   textbox11    74 non-null     str
dtypes: str(7)
memory usage: 4.2 KB

In [74]:
alerts['textbox4'].value_counts()

textbox4
Geofence Alert    62
Idle Alert        12
Name: count, dtype: int64

Possible mistake with Idle - Alert report

In [75]:
#plate=input('Type the number plate: ')
idle_alert_1=alerts[alerts['textbox4'].str.contains('Idle Alert')]
idle_alert_1.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\don_pollo\alert_report_filtered.csv')

In [76]:
hl=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\don_pollo\historicallocations.xlsx - Sheet1.csv',sep=',')
hl.info()

<class 'pandas.DataFrame'>
RangeIndex: 634 entries, 0 to 633
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sequence     634 non-null    int64
 1   Unit         634 non-null    str
 2   Events       634 non-null    str
 3   Date         634 non-null    str
 4   Landmark     224 non-null    str
 5   Address      634 non-null    str
 6   Speed        634 non-null    int64
 7   Temperature  0 non-null      float64
 8   Driver       634 non-null    str
 9   Latitude     634 non-null    float64
 10  Longitude    634 non-null    float64
dtypes: float64(3), int64(2), str(6)
memory usage: 54.6 KB

In [77]:
hl['Events'].value_counts()

Events
Drive           297
Travel Start     60
Travel Stop      57
Landmark OUT     36
Ignition OFF     35
Ignition ON      35
Landmark IN      28
Geofence OUT     25
Geofence IN      25
Idle - Stop      14
Parked           12
Idle Alert        9
POWER UP          1
Name: count, dtype: int64

In [78]:
hl_travel_start=hl[hl['Events'].str.contains('Idle - Stop')]
hl_travel_start[['Date','Unit','Events','Speed']]

                     Date     Unit       Events  Speed
8    May 14 2026 08:29 AM  BCY-928  Idle - Stop      0
14   May 14 2026 08:13 AM  BCY-928  Idle - Stop      0
54   May 14 2026 06:56 AM  BCY-928  Idle - Stop      0
65   May 14 2026 06:44 AM  BCY-928  Idle - Stop      0
78   May 14 2026 06:21 AM  BCY-928  Idle - Stop      0
197  May 14 2026 03:23 AM  BCY-928  Idle - Stop      0
220  May 13 2026 12:02 PM  BCY-928  Idle - Stop      0
252  May 13 2026 11:14 AM  BCY-928  Idle - Stop      0
259  May 13 2026 10:58 AM  BCY-928  Idle - Stop      0
461  May 13 2026 07:00 AM  BCY-928  Idle - Stop      0
470  May 13 2026 06:55 AM  BCY-928  Idle - Stop      0
490  May 13 2026 06:39 AM  BCY-928  Idle - Stop      0
585  May 13 2026 04:43 AM  BCY-928  Idle - Stop      6
630  May 13 2026 03:23 AM  BCY-928  Idle - Stop      0

In [79]:
hl_idle_alert=hl[hl['Events'].str.contains('Alert')]
hl_idle_alert[['Date','Unit','Events','Speed']]

                     Date     Unit      Events  Speed
13   May 14 2026 08:15 AM  BCY-928  Idle Alert      0
53   May 14 2026 06:58 AM  BCY-928  Idle Alert      0
61   May 14 2026 06:46 AM  BCY-928  Idle Alert      0
77   May 14 2026 06:23 AM  BCY-928  Idle Alert      0
196  May 14 2026 03:25 AM  BCY-928  Idle Alert      0
219  May 13 2026 12:04 PM  BCY-928  Idle Alert      0
251  May 13 2026 11:16 AM  BCY-928  Idle Alert      0
460  May 13 2026 07:02 AM  BCY-928  Idle Alert      0
629  May 13 2026 03:25 AM  BCY-928  Idle Alert      0

Idle alert:

In [80]:
unit=pd.read_excel(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\don_pollo\Export.xlsx') #For xls files.
idle_alert_events=pd.DataFrame()

event_code=[]
date_event_code=[]

for i in range(0,unit.shape[0]):
    #event_code.append(unit.iloc[i,2][64:68])
    if unit.iloc[i,2][64:66]=='2D': # Put the Even Code to look for.
        event_code.append(unit.iloc[i,2][64:66])
        date_event_code.append(unit.iloc[i,0])
        #print(unit.iloc[i,2][64:66],' -> ',unit.iloc[i,0])


idle_alert_events['Date']=date_event_code
idle_alert_events['Event']=event_code

idle_alert_events.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\don_pollo\idle_alert_events.csv')

print(idle_alert_events)

                      Date Event
0  2026-05-13 08:24:20.917    2D
1  2026-05-13 12:02:53.099    2D
2  2026-05-13 16:15:29.916    2D
3  2026-05-13 17:04:08.623    2D
4  2026-05-14 08:24:37.782    2D
5  2026-05-14 11:22:32.245    2D
6  2026-05-14 11:46:49.962    2D
7  2026-05-14 11:58:59.916    2D
8  2026-05-14 13:14:16.054    2D
9  2026-05-14 14:21:44.128    2D